# config/aws.yml
defaults: &defaults
  access_key_id: "AKIAJ66VG7DN6CDL2OEQ"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "getitdonebunyan"
test:
  <<: *defaults
  bucket: "getitdonebunyan"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "getitdonebunyan"