# config/aws.yml
defaults: &defaults
  access_key_id: ""
  secret_access_key: ""
development:
  <<: *defaults
  bucket: "getitdonebunyan"
test:
  <<: *defaults
  bucket: "getitdonebunyan"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "getitdonebunyan"